name: Truth Finder CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 582129522735.dkr.ecr.ap-south-1.amazonaws.com
  BACKEND_REPO: truth-finder-server
  FRONTEND_REPO: truth-finder-client

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region "$AWS_REGION" |
          docker login --username AWS --password-stdin "$ECR_REGISTRY"

      - name: Build backend image
        run: |
          docker build \
            --no-cache \
            -f ./server/Dockerfile \
            -t "$BACKEND_REPO:latest" \
            .

      - name: Build frontend image
        run: |
          docker build \
            --no-cache \
            -f ./client/Dockerfile \
            -t "$FRONTEND_REPO:latest" \
            .

      - name: Push backend image
        run: |
          docker tag "$BACKEND_REPO:latest" \
            "$ECR_REGISTRY/$BACKEND_REPO:latest"

          docker push \
            "$ECR_REGISTRY/$BACKEND_REPO:latest"

      - name: Push frontend image
        run: |
          docker tag "$FRONTEND_REPO:latest" \
            "$ECR_REGISTRY/$FRONTEND_REPO:latest"

          docker push \
            "$ECR_REGISTRY/$FRONTEND_REPO:latest"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/truth-finder

            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS --password-stdin \
            582129522735.dkr.ecr.ap-south-1.amazonaws.com

            docker pull \
            582129522735.dkr.ecr.ap-south-1.amazonaws.com/truth-finder-server:latest

            docker pull \
            582129522735.dkr.ecr.ap-south-1.amazonaws.com/truth-finder-client:latest

            docker-compose up -d

            docker image prune -f

            docker-compose ps